name: 🚀 DevOps-Ready Feature Request
description: Create a comprehensive, DevOps-integrated issue for new features
title: "[FEATURE] 🚀 "
labels: ["feature", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        # 🚀 DevOps-Ready Feature Implementation
        
        > **📋 Instructions:** Fill out ALL sections below to ensure comprehensive DevOps planning and implementation.

  - type: textarea
    id: overview
    attributes:
      label: "🎯 Overview"
      description: "Provide a clear, concise description of the feature/capability being implemented"
      placeholder: "Describe the feature or capability you want to implement..."
    validations:
      required: true

  - type: checkboxes
    id: current-state
    attributes:
      label: "📊 Current State Analysis"
      description: "Document the existing state and limitations"
      options:
        - label: "Current implementation documented"
        - label: "Known limitations identified"
        - label: "Performance constraints analyzed"
        - label: "User experience gaps documented"

  - type: textarea
    id: business-impact
    attributes:
      label: "🔍 Business Impact"
      description: "How does this improve user experience, business metrics, or operational efficiency?"
      placeholder: "Explain the business value and impact..."
    validations:
      required: true

  - type: textarea
    id: technical-necessity
    attributes:
      label: "⚙️ Technical Necessity"
      description: "What technical requirements drive this need?"
      placeholder: "Explain the technical drivers and requirements..."
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "✅ Acceptance Criteria"
      description: "List specific, measurable, testable requirements"
      placeholder: |
        **Core Functionality:**
        - [ ] [Component] - [Specific requirement with measurable outcome]
        - [ ] [API/Service] - [Functional requirement with performance target]
        
        **Performance Requirements:**
        - [ ] Response Time - [e.g., <500ms for API calls]
        - [ ] Throughput - [e.g., 1000 requests/second]
        
        **Security & Compliance:**
        - [ ] Authentication - [Authentication requirements]
        - [ ] Authorization - [Permission and access control]
    validations:
      required: true

  - type: checkboxes
    id: infrastructure-requirements
    attributes:
      label: "🏗️ Infrastructure Requirements"
      description: "Select all infrastructure components needed"
      options:
        - label: "Cloud Services (AWS/Azure/GCP)"
        - label: "Database services"
        - label: "Compute resources (Lambda, EC2, etc.)"
        - label: "Network configuration"
        - label: "Security services"
        - label: "Monitoring services"

  - type: checkboxes
    id: development-requirements
    attributes:
      label: "💻 Development Requirements" 
      description: "Select all development components needed"
      options:
        - label: "Backend services"
        - label: "API endpoints"
        - label: "Data models"
        - label: "Business logic"
        - label: "Integration services"
        - label: "Test suites"

  - type: textarea
    id: dependencies
    attributes:
      label: "🔗 Dependencies"
      description: "List blocking dependencies and related issues"
      placeholder: |
        **Blocking Dependencies:**
        - [ ] Issue Title (#IssueNumber) - Description of dependency
        
        **Related Issues:**
        - [ ] Issue Title (#IssueNumber) - How it relates
        
        **External Dependencies:**
        - [ ] External Service/API - Integration requirements

  - type: textarea
    id: implementation-plan
    attributes:
      label: "🚀 Implementation Plan"
      description: "Break down implementation into phases"
      placeholder: |
        **Phase 1: Infrastructure Setup** (Est: X days)
        - [ ] Task 1 - Description and acceptance criteria
        - [ ] Milestone: Infrastructure ready for development
        
        **Phase 2: Core Development** (Est: X days)
        - [ ] Task 1 - Description and acceptance criteria  
        - [ ] Milestone: Core functionality implemented
        
        **Phase 3: Integration & Testing** (Est: X days)
        - [ ] Task 1 - Description and acceptance criteria
        - [ ] Milestone: All tests passing and integration complete
        
        **Phase 4: Deployment & Monitoring** (Est: X days)
        - [ ] Task 1 - Description and acceptance criteria
        - [ ] Milestone: Feature deployed and monitored in production
    validations:
      required: true

  - type: textarea
    id: cost-estimation
    attributes:
      label: "💰 Cost Estimation"
      description: "Provide development and infrastructure cost estimates"
      placeholder: |
        **Development Costs:**
        - Engineering Time: X person-days
        - Testing & Validation: X person-days
        - Total Development: $X,XXX
        
        **Infrastructure Costs:**
        - Monthly Operational: $X - $X
        - Annual Estimate: $X,XXX
        
        **Risk Assessment:**
        - Technical Risks: [List key risks]
        - Timeline Risks: [Timeline concerns]

  - type: dropdown
    id: priority
    attributes:
      label: "🏷️ Priority"
      description: "Select the priority level"
      options:
        - critical
        - high
        - medium
        - low
    validations:
      required: true

  - type: dropdown
    id: effort
    attributes:
      label: "⏱️ Effort Estimate"
      description: "Select the estimated effort"
      options:
        - xs (1-2 hours)
        - s (3-8 hours)
        - m (1-2 days)
        - l (3-5 days)
        - xl (1-2 weeks)
        - xxl (>2 weeks)
    validations:
      required: true

  - type: checkboxes
    id: definition-of-done
    attributes:
      label: "📊 Definition of Done"
      description: "Check when complete"
      options:
        - label: "TypeScript compilation passes without errors"
        - label: "Unit tests achieve >90% code coverage"
        - label: "Integration tests pass all scenarios"
        - label: "Code review completed and approved"
        - label: "Security scan passes"
        - label: "Infrastructure configurations validated"
        - label: "Monitoring and alerting operational"
        - label: "Documentation complete"
        - label: "CI/CD pipeline updated and tested"
        - label: "Performance baselines established"

  - type: textarea
    id: success-metrics
    attributes:
      label: "📈 Success Metrics"
      description: "Define how success will be measured"
      placeholder: |
        **Technical Metrics:**
        - Performance: [Specific improvements]
        - Reliability: [Availability improvements]
        - Security: [Security enhancements]
        
        **Business Metrics:**
        - User Experience: [UX improvements]
        - Operational Efficiency: [Process improvements]
        - Cost Optimization: [Cost savings]
