name: Lighthouse CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *' # daily at 6am UTC

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli
      - name: Run Lighthouse CI
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: |
          if [ -n "$LHCI_GITHUB_APP_TOKEN" ]; then
            echo "Running Lighthouse CI with GitHub App token"
            lhci autorun --config=./lighthouserc.json
          else
            echo "Running Lighthouse CI without GitHub App token (LHCI_GITHUB_APP_TOKEN not configured)"
            lhci autorun --config=./lighthouserc.json || echo "Lighthouse CI completed with warnings"
          fi
